global:
  scrape_interval: 15s 
  external_labels:
    monitor: "ada-monitor"


scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "asw-ana-sigorta"
    metrics_path: /metrics/asw
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5137"]
  - job_name: "db-ana-sigorta"
    metrics_path: /metrics/db
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5137"]    
  - job_name: "ada-auth"
    metrics_path: /metrics/ada-auth
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5137"]