global:
  scrape_interval: 15s 
  external_labels:
    monitor: "ada-monitor"


scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "todo-api"
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:5137"]
